import dayjs from 'dayjs';
import checkOrCreateFolder from './checkOrCreateFolder';
import shouldShareFolder from './shouldShareFolder';
import googleFactory from '../factories/google';

const createBlankDocument = async () => {
  const emailAddressToShareWith = 'andreas@sapioweb.com';
  const folderName = `autoGeneratedResumes`;

  const folderId = await checkOrCreateFolder(folderName);

  if (!folderId) {
    throw new Error('Folder ID not found. Folder was not created or found.');
  }

  const shouldShare = await shouldShareFolder(
    folderId,
    emailAddressToShareWith
  );

  if (shouldShare) {
    // Share the folder
    await googleFactory.drive.permissions.create({
      requestBody: {
        type: 'user',
        role: 'writer',
        emailAddress: emailAddressToShareWith,
      },
      fileId: folderId,
      fields: 'id',
    });
  }

  const { data } = await googleFactory.documents.create({
    title: `Andreas Beasley Resume ${dayjs().unix()}`,
  });

  const documentId = data.documentId;

  if (!documentId) {
    throw new Error('Document ID not found. Document was not created.');
  }

  // Move the presentation to the folder
  await googleFactory.drive.files.update({
    fileId: documentId,
    addParents: folderId,
    removeParents: 'root',
    fields: 'id, parents',
  });

  console.info('Document created with ID:', documentId);

  return documentId;
};

export default createBlankDocument;
